body:
- attributes:
    value: 'Suggestion d amélioration.
      '
  type: markdown
- attributes:
    description: Une description précise de votre suggestion.
    label: Description
  type: textarea
  validations:
    required: true
- attributes:
    value: Avant de poster votre suggestion, passez en revue les étapes que vous avez écrites afin de vous assurer
      que les étapes fournies sont détaillées et claires.
  type: markdown
description: Créer un rapport d'amélioration
name: Suggestion
labels: ["enhancement"]
