body:
- attributes:
    value: 'Sur cette page vous pouvez décrire un bug recontré dans un de nos mods.'
  type: markdown
- attributes:
    label: Mod
    multiple: false
    options:
    - IXL2 - Kit d'optimisation - OMSI 2
    - Lite AI - DLC Saint-Servan
  type: dropdown
  validations:
    required: true
- attributes:
    description: Veuillez mettre la version du mod.
    label: Version du mod
  type: textarea
  validations:
    required: true
- attributes:
    description: Une description précise du bug.
    label: Description
  type: textarea
  validations:
    required: true
- attributes:
    description: Étapes afin de reproduire le bug, veuillez mettre une description claire
      afin de reproduire le bug. Les screenshots
      peuvent être inclus.
    label: Étapes à reproduire
  type: textarea
  validations:
    required: true
- attributes:
    description: Une description claire et concise sur le comportement du mod sans bug.
    label: Comportement attendu
  type: textarea
  validations:
    required: true
- attributes:
    description: Non obligatoire, mais si possible suggérez un correctif ou une raison pour le bug.
    label: Solution possible
  type: textarea
  validations:
    required: false
- attributes:
    value: Avant de poster le problème, passez en revue les étapes que vous avez écrites afin de vous assurer
      que les étapes fournies sont détaillées et claires.
  type: markdown
description: Créer un rapport de bug
name: Rapport de bug
labels: ["bug"]
